### PR TITLE
Add image into README.md

### PR DESCRIPTION
**Pull request by mizorin**
I designed the icon for BitcoinCashKit

img_bitcoincashkit

### CODE REVIEW

**Comment by usatie** [comment]
@GitCash send .100 bits to @mizorin

**Comment by GitCash** [comment]
Hey **mizorin**, user **usatie** tipped you **0 bits** in Bitcoin Cash ( ~ **$0.0001** ).

*[Click here to claim it!](https://gitcash.io/claim/mizorin)*

You can also add the "thumbs down" reaction to **usatie**'s comment above to prevent future tips.

**Comment by usatie** [comment]
GitCash send 100 bits to @mizorin

**Comment by usatie** [comment]
@GitCash send 15000 bits to @mizorin

**Comment by usatie** [comment]
@GitCash send 15000 bits to @mizorin

**Comment by GitCash** [comment]
Hey **mizorin**, user **usatie** tipped you **15000 bits** in Bitcoin Cash ( ~ **$12.3** ).

*[Click here to claim it!](https://gitcash.io/claim/mizorin)*

You can also add the "thumbs down" reaction to **usatie**'s comment above to prevent future tips.

**Pull request merged**
