### PR TITLE
Divided tests to each class

### PR DESCRIPTION
**Pull request by kzumu**
@usatie Hi!
I divided tests to each class.
Would you review this?

### CODE REVIEW

**Comment by kzumu** [comment]
Ok, sorry.
I got it.
I remove my name.

**Comment by kzumu** [comment]
Thanks!

**Comment by usatie** [comment]
@GitCash send 10000 bits to @kzumu

**Comment by GitCash** [comment]
Hey **kzumu**, user **usatie** tipped you **10000 bits** in Bitcoin Cash ( ~ **$7.6** ).

*[Click here to claim it!](https://gitcash.io/claim/kzumu)*

You can also add the "thumbs down" reaction to **usatie**'s comment above to prevent future tips.

**Pull request merged**
